### ISSUE TITLE
Bug on PrettyFormatPluginError

### ISSUE THREAD

**Issue by behnammodi** [cssinjs/jss-snapshot-serializer#7]
I got this error after use this package:

![Screen Shot 2021-06-27 at 13 21 53](https://user-images.githubusercontent.com/1549069/123538551-b9d18580-d74a-11eb-810f-d0da359079ce.png)

**Comment by kof** [comment]
please follow the steps when creating issues, we need a full info, otherwise this is not useful, feel free to reopen one you provide it

**Comment by kof** [comment]
Sorry in this repo we haven't added an issue template, please use this one https://github.com/cssinjs/jss/issues/new?assignees=&labels=&template=---bug-report.md
